-ifndef(DEFAULT_IMPORTS).
-define(DEFAULT_IMPORTS,
"import Maybe.\n"
"alias Maybe a = Maybe.Maybe a.\n"
"import Core.\n"
"alias Integer = Core.Integer.\n"
"alias String = Core.String.\n"
"alias Unit = Core.Unit.\n"
"alias Never = Core.Never.\n"
"alias Boolean = Core.Boolean.\n"
"let |> = Core.|>.\n"
"let <| = Core.<|.\n"
"let not = Core.not.\n"
"let and = Core.and.\n"
"let or = Core.or.\n"
"let xor = Core.xor.\n"
"let always = Core.always.\n"
"let == = Core.==.\n"
"let <> = Core.<>.\n"
"let compare = Core.compare.\n"
"let > = Core.>.\n"
"let >= = Core.>=.\n"
"let < = Core.<.\n"
"let <= = Core.<=.\n"
"let + = Core.+.\n"
"let * = Core.*.\n"
"let / = Core./.\n"
"let // = Core.//.\n"
"let - = Core.-.\n"
"let ^ = Core.^.\n"
"let ^^ = Core.^^.\n"
"let abs = Core.abs.\n"
"import List.\n"
"alias List a = List.List a.\n"
"\n").
-endif.
